#!/bin/bash
myvar="a value"
declare -i count=0
while read line; do
  echo "$myvar: $line"
  count+=1
# creates a tmp file with the grep output 
done <<< $(grep something somefile)
echo "Count: $count"
