#!/usr/bin/python3


'''

check for special arguments

if there *isn't* a first argument
    print 'Hey there'
    exit or return

if the first argument is 'Rob'
   print 'Hey bro, Rob, you rock!' 
   exit

if the first argument is 'Dork'
    print 'dude be nice'
    exit

'''

'''
check for special arguments

if the first argument is Rob
    print 'hey bro'
else if first argument is Dork
    print 'dude be nice'
else
    print 'hey there'

'''

'''

get the first argument

switch first argument {
case 'Rob':
    msg  = 'hey bro' 
case 'Dork':
    msg =  'dude be nice'
default:
    msg = 'hey there'
}

print msg

'''
