#!/bin/bash

declare -r clear=$'\033[H\033[2J'
declare -r red=$'\033[38;2;255;0;0m'
declare -r green=$'\033[38;2;0;255;0m'
declare -r blue=$'\033[38;2;0;0;255m'
declare -r white=$'\033[38;2;255;255;255m'
declare -r reset=$'\033[0m'

# echo -e $"\033[38;2;$red;$green;${blue}m"

## Script to help print the actual color binary ANSI
## escapes as well as the text equivalent suitable
## from pasting into scripts providing stand-alone
## color support.

#TODO hex2dec conversion
# $((16#$hexNum))
# hex=f0;dec=`bc<<<"ibase=16;${hex^^}"`; echo $dec
# printf "%i\n" 0xff

## CSS Hex Value
if [[ $# == 1 ]]; then
  case ${#1} in
    6) echo six ;;
    3) echo three ;;
    1) echo one ;;
    *) echo "${red}Must be 1, 3, or 6 in length.$reset"
       exit 1 ;;
  esac
  exit 0
fi

## RGB Value
if [[ $# == 3 ]]; then
  declare r="$1"
  declare g="$2"
  declare b="$3"
  # TODO validate
  echo -e $"\033[38;2;$r;$g;${b}m"
  exit 0
fi

## Something was not right above
echo 'usage: color HEX'
echo '       color RED GREEN BLUE'
echo '  (HEX can be len 6,3,1)'
exit 1
