#!/bin/bash

# single argument (hex)

for i in f ff fff ffff fffff ffffff; do
  echo '------------------------------------------'
  echo Testing $i
  ./color $i; echo $?
done

# three arguments (rgb)

echo '------------------------------------------'
echo Testing white
./color 255 255 255; echo $?

echo '------------------------------------------'
echo Testing red
./color 255 0 0; echo $?

echo '------------------------------------------'
echo Testing green
./color 0 255 0; echo $?

echo '------------------------------------------'
echo Testing blue
./color 0 0 255; echo $?

# RGB edge cases

echo '------------------------------------------'
echo Testing red out of bounds
./color 300 0 0; echo $?
./color -2 0 0; echo $?

echo '------------------------------------------'
echo Testing green out of bounds
./color 0 300 0; echo $?
./color 0 -2 0; echo $?

echo '------------------------------------------'
echo Testing blue out of bounds
./color 0 0 300; echo $?
./color 0 0 -2; echo $?

echo '------------------------------------------'
echo Testing Just 2 arguments
./color 0 0; echo $?

echo '------------------------------------------'
echo 'Testing >3 arguments'
./color 0 0 0 0; echo $?

echo '------------------------------------------'
echo 'Testing none numeric arguments'
./color abc 0 0; echo $?
./color 0 abc 0; echo $?
./color 0 0 abc; echo $?
./color 0 0 pi; echo $?

