#!/bin/bash

declare -r clear=$'\033[H\033[2J'
declare -r red=$'\033[38;2;255;0;0m'
declare -r green=$'\033[38;2;0;255;0m'
declare -r blue=$'\033[38;2;0;0;255m'
declare -r white=$'\033[38;2;255;255;255m'
declare -r reset=$'\033[0m'

echo "${clear}${green}Do you like waffles?${white}"
read answer

declare -r yes='^y(e(s|p(pers)?|ah))?$'

if [[ "${answer,,}" =~ $yes  ]]; then
  echo "${green}Do you like pancakes?$reset"
  read answer
fi

if [[ "${answer,,}" =~ $yes  ]]; then
  echo "${green}Do you like French toast?$reset"
  read answer
fi

if [[ "${answer,,}" =~ $yes  ]]; then
  echo "${green}Doot do da doot can't wait to get a mouthful.$reset"
  declare -i i=0                             # init
  while true; do
    #sleep 2
    echo "${green}Waffles! (count $i)"
    i=i+1                                    # change
    if [[ $i < 3 ]]; then                    # check (condition)
      continue
    else
      break
    fi
    echo something random # never actually runs
  done
  exit 1
fi

echo "${red}Okay then.$reset"
exit 1
