#!/bin/bash

<<algorithm1
if there is an argument then 
  if the argument is either 'Rob' or 'Linus' then print 'you rock'
  else if argument is 'Dork' then print 'you rude'
  else print 'Hi' plus the argument.
else print 'Hi there'.
algorithm1

<<algorithm2
if there are no arguments then print 'Hi there' and exit
if argument is 'Rob' or 'Linus' then print 'you rock' and exit
if argument is 'Dork' and print 'you rude' and exit
print 'Hi' and the argument
algorithm2

if [[ -z "$1" ]]; then
  echo 'Hi there.'
  exit
fi

if [[ "$1" == Rob || "$1" == Linus ]]; then
  echo "What $1, you rock!"
  exit
fi

if [[ "$1" == Dork ]]; then
  echo "Um, no need to be rude."
  exit
fi

echo "Hi $1"

<<withcase
[[ -z "$1" ]] && echo 'Hi there.' && exit
case "$1" in
  Dork) echo 'Um, no need to be rude.';;
  Special) echo 'Woah Special, you rock!';;
  *) echo "Hi $1.";;
esac
withcase
